/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * SphereFinVest API
 * API documentation for StartupVest, FinEase, and StartupSphere
 * OpenAPI spec version: 1.0
 */
import type { User } from "./user";

export interface Activity {
  action: string;
  details: string;
  id: number;
  timestamp: string;
  user: User;
}
