/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * SphereFinVest API
 * API documentation for StartupVest, FinEase, and StartupSphere
 * OpenAPI spec version: 1.0
 */
import type { FundingRound } from "./fundingRound";
import type { Investor } from "./investor";
import type { User } from "./user";

export interface CapTableInvestor {
  capTable: FundingRound;
  createdAt: string;
  id: number;
  investor: Investor;
  investorRemoved: boolean;
  isDeleted: boolean;
  shares: number;
  status: string;
  title: string;
  totalInvestment: number;
  user: User;
}
