/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * SphereFinVest API
 * API documentation for StartupVest, FinEase, and StartupSphere
 * OpenAPI spec version: 1.0
 */
import type { CapTableInvestor } from "./capTableInvestor";
import type { Investor } from "./investor";
import type { Startup } from "./startup";

export interface FundingRound {
  announcedDate: string;
  capTableInvestors: CapTableInvestor[];
  closedDate: string;
  createdAt: string;
  fundingName: string;
  fundingType: string;
  id: number;
  investors: Investor[];
  isDeleted: boolean;
  minimumShare: number;
  moneyRaised: number;
  moneyRaisedCurrency: string;
  preMoneyValuation: number;
  startup: Startup;
  targetFunding: number;
}
