/**
 * Generated by orval v7.1.0 🍺
 * Do not edit manually.
 * StartupSphere API
 * API documentation for StartupSphere, the 3D mapping platform for startup ecosystems.
 * OpenAPI spec version: 1.0
 */

export interface Investor {
  id: number;
  name: string;
  description: string;
  type: string;
  investment_focus: string;
  total_funds: number;
  locationLat: number;
  locationLng: number;
  locationName: string;
  websiteUrl: string;
  logoUrl: string;
  contactInfo: string;

  //createViewRequest, createLikeRequest, createBookmarkRequest
}
