/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * SphereFinVest API
 * API documentation for StartupVest, FinEase, and StartupSphere
 * OpenAPI spec version: 1.0
 */
import type { CapTableInvestor } from "./capTableInvestor";
import type { FundingRound } from "./fundingRound";
import type { ProfilePicture } from "./profilePicture";
import type { User } from "./user";

export interface Investor {
  biography: string;
  bookmarks: number;
  capTableInvestors: CapTableInvestor[];
  city: string;
  contactInformation: string;
  country: string;
  emailAddress: string;
  facebook: string;
  firstName: string;
  fundingRounds: FundingRound[];
  gender: string;
  id: number;
  instagram: string;
  isDeleted: boolean;
  lastName: string;
  likes: number;
  linkedIn: string;
  locationLat: number;
  locationLng: number;
  locationName: string;
  postalCode: string;
  profilePicture: ProfilePicture;
  state: string;
  streetAddress: string;
  twitter: string;
  user: User;
  views: number;
  website: string;
}
