/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * SphereFinVest API
 * API documentation for StartupVest, FinEase, and StartupSphere
 * OpenAPI spec version: 1.0
 */

export interface Report {
  generated_by: number;
  id: number;
  name: string;
  timestamp: string;
  content: string;
}
