/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * StartupSphere API
 * API documentation for StartupSphere, the 3D mapping platform for startup ecosystems.
 * OpenAPI spec version: 1.0
 */
import type { User } from "./user";

export interface Report {
  file_type: string;
  generated_by: User;
  id: number;
  name: string;
  timestamp: string;
  url: string;
}
