/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * StartupSphere API
 * API documentation for StartupSphere, the 3D mapping platform for startup ecosystems.
 * OpenAPI spec version: 1.0
 */

export interface StartupRequest {
  capital: number;
  categories: string[];
  contactInfo: string;
  description: string;
  foundedDate: string;
  founderName: string;
  fundingStage: string;
  locationLat: number;
  locationLng: number;
  locationName: string;
  logoUrl: string;
  managerId?: number;
  name: string;
  teamSize: number;
  websiteUrl: string;
}
