/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * StartupSphere API
 * API documentation for StartupSphere, the 3D mapping platform for startup ecosystems.
 * OpenAPI spec version: 1.0
 */

export interface StartupRequest {
  categories: string[];
  contactInfo: string;
  description: string;
  foundedDate: string;
  founderName: string;
  locationLat: number;
  locationLng: number;
  locationName: string;
  logoUrl: string;
  name: string;
  websiteUrl: string;
}
