/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * SphereFinVest API
 * API documentation for StartupVest, FinEase, and StartupSphere
 * OpenAPI spec version: 1.0
 */
import type { FundingRound } from "./fundingRound";
import type { ProfilePicture } from "./profilePicture";
import type { User } from "./user";

export interface Startup {
  bookmarks: number;
  city: string;
  companyDescription: string;
  companyName: string;
  contactEmail: string;
  country: string;
  facebook: string;
  foundedDate: string;
  fundingRounds: FundingRound[];
  id: number;
  industry: string;
  instagram: string;
  isDeleted: boolean;
  likes: number;
  linkedIn: string;
  locationLat: number;
  locationLng: number;
  locationName: string;
  numberOfEmployees: string;
  phoneNumber: string;
  postalCode: string;
  profilePicture: ProfilePicture;
  startupCode: string;
  state: string;
  streetAddress: string;
  twitter: string;
  typeOfCompany: string;
  user: User;
  views: number;
  website: string;
}
