/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * SphereFinVest API
 * API documentation for StartupVest, FinEase, and StartupSphere
 * OpenAPI spec version: 1.0
 */
import type { Activity } from "./activity";
import type { CapTableInvestor } from "./capTableInvestor";
import type { Investor } from "./investor";
import type { ProfilePicture } from "./profilePicture";
import type { Startup } from "./startup";

export interface User {
  activities: Activity;
  capTableInvestor: CapTableInvestor;
  contactNumber: string;
  createdAt: string;
  email: string;
  firstName: string;
  gender: string;
  id: number;
  investor: Investor;
  isVerified: boolean;
  lastName: string;
  password?: string;
  profilePicture: ProfilePicture;
  resetPasswordExpires?: string;
  resetPasswordToken?: string;
  role: string;
  startupCode?: string;
  startups: Startup[];
}
