/**
 * Generated by orval v6.28.2 🍺
 * Do not edit manually.
 * StartupSphere API
 * API documentation for StartupSphere, the 3D mapping platform for startup ecosystems.
 * OpenAPI spec version: 1.0
 */

export interface User {
  avatarUrl: string;
  createdAt: string;
  email: string;
  firstName: string;
  id: number;
  lastName: string;
  moderator: boolean;
}
